### ISSUE TITLE
Speedup for $K=0$

### ISSUE THREAD

**Issue by tlunet** [Parallel-in-Time/time4apint#11]
Currently the `speedup` method of `BlockIteration` returns a very high value for $K=0$ (for instance, in the `03_pinIter.py` script, it gives a speedup of 20 for 10 blocks, independently on the `schedule_type`.

Normally it should be 

```math
\frac{C_{serial}}{C_{initialGuess}}
```

is it possible to implement this easily @JensHahne  ?

**Comment by JensHahne** [comment]
Sorry, i dont get this. For me it holds:

Speedup = Cost_serial / Cost_parallel

So, if i have a good solution after K=0 (so after computing the initial guess), it should be a big speedup?!

**Comment by JensHahne** [comment]
Ah, i got it. Both formulars should be the same.

So it depends on the cost of the operators what the speedup is. I can look at the example later, but i think it should be implemented the way you want.

**Comment by tlunet** [comment]
In Parareal, how do you get the speedup for $K=0$ ? By running the coarse solver only :wink:. Except if you use zero or random initial guess (in that case, speedup is infinite ...)

**Comment by JensHahne** [comment]
Yes, you are right. But i think then the speedup should be implemented the way you want. But of course it always depends on the cost of an operator, which is think is choosen a little random depending on the method of G and F.

**Comment by tlunet** [comment]
Oh, nevermind : your schedulers actually give the correct implementation for $K=0$, sorry :sweat_smile:
