### ISSUE TITLE
Presentation details

### ISSUE THREAD

**Issue by tlunet** [Parallel-in-Time/time4apint#13]
Hey @JensHahne, just writing here some idea(s) for siam presentation :

- [ ] maybe don't represent in task graph the tasks that cost nothing. This should allow a simpler/clearer representation while making explicit only the costly operations (a bit like the scheduling graph)

**Comment by JensHahne** [comment]
To be honest, I'm not a big fan of this. Even if the cost is zero, the information in the task graph is important. The dependency information that results from these tasks cannot be removed. Also, there could be communication costs, etc., although we haven't considered that yet.

Anyway, I will give you both task diagrams tomorrow. At the end, you can decide which one you want to use for the presentation.

**Comment by tlunet** [comment]
I agree ! I was just wondering if there could be an option to hide the zero-cost tasks, just for simpler model. Then those would be shown as soon as their cost is set to a non-zero value, or if the graph option to hide the non-zero tasks is deactivated.

At least a middle ground could be to set a convention color/symbol shape to represent the task for which we did not set a cost ... ?
