### ISSUE TITLE
Cannot get apps webpage in local dev website

### ISSUE THREAD

**Issue by tlunet** [Parallel-in-Time/time4apint#19]
@MichelKrispin after installing a clean environment with the `requirements.txt`, when launching the website with

```bash
python web.py
```

the index webpage is displayed, but the `accuracy` or `demo` app shows a blank page. Here is the firefox console log for `accuracy` for instance :

![image](https://github.com/Parallel-in-Time/time4apint/assets/12183839/9f09bd0f-9a4c-4e67-918c-72340c245ecf)

**Comment by tlunet** [comment]
PS : I guess I'm missing the build of the TS part, but I did not find the updated documentation on this ... :sweat_smile:

**Comment by MichelKrispin** [comment]
@tlunet Sorry for the late answer.
I updated the way the server works and it should take the built Javascript files now by default. There are some problems right now with them (the icons aren't displayed right now; the buttons for home and documentation in the upper corners are there but without icons and the error pop-up isn't shown) but I will look into that.
So running
```sh
python web.py
```
should work now.

Additionally, I updated the `dev-documentation.md`, so following that should also work.

Let me know if there are still error messages coming up.

**Comment by tlunet** [comment]
On which branch did you push ? I don't see anything new in the `web` branch (see https://github.com/Parallel-in-Time/time4apint/tree/web) ...

**Comment by MichelKrispin** [comment]
I merged it all into the `gaia` branch in [this](https://github.com/Parallel-in-Time/time4apint/commit/97fe8fa157adb834106641aa943540d7a991a5ca) commit.

**Comment by tlunet** [comment]
Oh I see :sweat_smile: ... should we ignore the `web` branch now then ?

**Comment by MichelKrispin** [comment]
Yes, I mean I don't use it anymore. Maybe for some experimental feature thats about to come there is some use for it but then we could also create a new branch when the time has come.

**Comment by tlunet** [comment]
Btw, `accuracy` app seems not to be in `web_apps` folder : should I recreate it based on the `demo` app or do you still have an old one that can be used as basis ?

**Comment by MichelKrispin** [comment]
I'm currently working on that, i.e. I created one that takes the block problem parameters and generates the frontend. 
I can upload that but right now there is a problem with the displayed graph...

**Comment by tlunet** [comment]
Don't worry : I can still use it for the demonstration, even if the graph is not the correct one. I have the python script to do the proper run and show the real graphs anyway. So you can already push it and correct it later.

Other point : when trying to build the dev frontend, got this error :

```bash
(base) telu@calliope:frontend$ which yarn
/usr/bin/yarn
(base) telu@calliope:frontend$ ls
node_modules  package.json  src  tsconfig.json  tsconfig.node.json  vite.config.ts  yarn.lock
(base) telu@calliope:frontend$ yarn 
00h00m00s 0/0: : ERROR: There are no scenarios; must have at least one.
```

**Comment by MichelKrispin** [comment]
Ok. I just pushed the base app. It should be there now (without documentation right now).

Actually, I haven't seen that before... But I can reproduce it!
If I also use `yarn` from `/usr/bin/yarn` I get the same error message. My default `yarn` which works is inside my node installation at `/home/michel/node-v18.14.../bin/yarn`.

Just to be sure. Does at least the non-dev version work?

**Comment by tlunet** [comment]
Actually, doing `python web.py` works already. But thanks ! I'll use the correct yarn then ...

**Comment by MichelKrispin** [comment]
With the latest updates the plot should work correctly too. And the icons should be displayed.
If there is another problem with getting the frontend up and running, let me know.

**Comment by tlunet** [comment]
Ok, solved the `yarn` problem. The version shipped with linux distro (Ubuntu in my case) is actually very old. So using a more recent version, installed _e.g_ with `npm`, solve the issue :

```bash
(base) telu@calliope:frontend$ /usr/bin/yarn --version
0.32+git
(base) telu@calliope:frontend$ /usr/local/bin/yarn --version
1.22.19
```
