### ISSUE TITLE
Possibility to add caption text (markdown format) for the plots

### ISSUE THREAD

**Issue by tlunet** [Parallel-in-Time/time4apint#23]
Some additional `caption` string argument for the `PlotsStage` constructor, that would be used to display a caption below the figure, and could support markdown format (for instance, when using latex inline formula)

**Comment by MichelKrispin** [comment]
At least for now it is possible to add a text (no LaTeX) caption by adding the `xaxis_title` parameter to the `fig.update_layout` function such as
```python
fig.update_layout(
    margin=dict(l=0, r=0, b=0, t=0),
    height=450,
    xaxis_title="Some text caption",
)
```
But a separate caption with LaTeX support would definitely be helpful.

**Comment by MichelKrispin** [comment]
`stages.PlotsStage` has now an additional argument `caption` which can include LaTex and markdown.
I've added a bit of documentation in the `demo.py` file.
Now, it's also possible to use this as a result stage. It's not really clean, but if the plot in the `PlotStage` is `None` and the caption is set, then this caption will be used as a full-scale result display including multiline equations etc. (without the fullscreen button attached)
